---
- name: Provision Hashicorp Consul Server
  hosts: all

  vars:
    # Taken from:
    # https://www.consul.io/docs/agent/options.html#ports-used
    ufw_allowed_ports:
      - port: 8300
        proto: tcp
      - port: 8301
        proto: tcp
      - port: 8301
        proto: udp
      - port: 8302
        proto: tcp
      - port: 8302
        proto: udp
      - port: 8500
        proto: tcp
      - port: 8600
        proto: tcp
      - port: 8600
        proto: udp

  pre_tasks:
    - name: Update package list
      become: true
      apt:
        update_cache: true

  roles:
    - ufw
    - hashicorp-consul
